# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_test"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: "Build"
        run: cmake --version && cmake -S . -B build && cmake --build build

      - name: "Run unit tests"
        run:
          ./build/tests/umbra_assessment_tests --gtest_shuffle --gtest_break_on_failure --gtest_repeat=3 --gtest_output="xml:umbra.xml"

      - name: 'Upload unit test results'
        uses: actions/upload-artifact@v4
        with:
          name: "gtest_output"
          path: "umbra.xml"